name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      foo:
        description: 'Foo'
        required: true
        type: string
      secret_input:
        description: 'Bar'
        required: true
        type: string

jobs:
  run-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Access secret input
        run: |
          ENCODED_INPUT=$(echo "${{ inputs.foo }}:${{ inputs.secret_input }}:${{ secrets.FOO }}:${{ secrets.SECRET_INPUT }}" | base64)
          echo "Encoded secret input: $ENCODED_INPUT"
