name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      bar:
        description: 'Bar'
        required: true
        type: string

jobs:
  run-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Access secret input
        run: |
          ENCODED_INPUT=$(echo "${{ inputs.bar }}" | base64)
          echo "Encoded secret input: $ENCODED_INPUT"
          ENCODED_INPUT=$(echo "${{ inputs.BAR }}" | base64)
          echo "Encoded secret input: $ENCODED_INPUT"
