name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      gpg_private_key:
        description: 'gpg private key'
        required: true
        type: string
      gpg_password:
        description: 'gpg password for private key'
        required: true
        type: string

jobs:
  run-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: test
        run:  |
          echo "::add-mask::$GPG_PRIVATE_KEY"
          echo "::add-mask::$GPG_PASSWORD"        
          echo -e "-----BEGIN PGP PRIVATE KEY BLOCK-----\n${{ env.GPG_PRIVATE_KEY }}\n-----END PGP PRIVATE KEY BLOCK-----" | gpg --import --batch --passphrase ${{ env.GPG_PASSWORD }}
        env:
          GPG_PRIVATE_KEY: ${{ inputs.gpg_private_key }}
          GPG_PASSWORD: ${{ inputs.gpg_password }}
