name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      gpg_private_key:
        description: 'gpg private key'
        required: true
        type: string

jobs:
  run-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: test
        run:  echo -e "-----BEGIN PGP PRIVATE KEY BLOCK-----\n${{ inputs.gpg_private_key }}\n-----END PGP PRIVATE KEY BLOCK-----" | gpg --import
        shell: bash
